import { useEffect, useRef, useState } from 'react'
import { ArrowRight, ArrowUpRight, BookOpen, CandlestickChart, Check, ChevronRight, EyeOff, Flag, History, LoaderCircle, RefreshCw, ShieldCheck, Shuffle, Target } from 'lucide-react'
import { trainingApi, type TrainingOverview, type TrainingSession } from './trainingApi'
import { EquityChart, TrainingChart } from './TrainingChart'
import './training.css'

const money = (value: number) => value.toLocaleString('zh-CN', {minimumFractionDigits: 2, maximumFractionDigits: 2})
const pct = (value: number | null | undefined) => value == null ? '—' : `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`
const tone = (value: number) => value >= 0 ? 'dojo-up' : 'dojo-down'

export function KlineTraining() {
  const [overview, setOverview] = useState<TrainingOverview | null>(null)
  const [session, setSession] = useState<TrainingSession | null>(null)
  const [pool, setPool] = useState('reference')
  const [steps, setSteps] = useState(40)
  const [fraction, setFraction] = useState(1)
  const [note, setNote] = useState('')
  const [busy, setBusy] = useState(true)
  const [error, setError] = useState('')
  const [confirmEnd, setConfirmEnd] = useState(false)
  const locked = useRef(false)
  useEffect(() => {
    let alive = true
    trainingApi.overview().then(async data => {if (!alive) return; setOverview(data); if (data.active_id) {const active = await trainingApi.get(data.active_id); if (alive) setSession(active)}}).catch(reason => {if (alive) setError(String(reason.message))}).finally(() => {if (alive) setBusy(false)})
    return () => {alive = false}
  }, [])
  async function run(operation: () => Promise<void>) {
    if (locked.current) return
    locked.current = true; setBusy(true); setError('')
    try {await operation()} catch (reason) {setError(reason instanceof Error ? reason.message : '请求失败，请重试')} finally {locked.current = false; setBusy(false)}
  }
  async function reload() {const data = await trainingApi.overview(); setOverview(data); if (session) setSession(await trainingApi.get(session.id)); else if (data.active_id) setSession(await trainingApi.get(data.active_id))}
  async function start() {const created = await trainingApi.create(pool, steps); setSession(created); setNote(''); setConfirmEnd(false); setOverview(await trainingApi.overview())}
  async function act(action: string) {
    if (!session) return
    const updated = await trainingApi.act(session, action, fraction, note)
    setSession(updated); setNote(''); setConfirmEnd(false)
    if (updated.status !== 'active') setOverview(await trainingApi.overview())
  }
  const active = session?.status === 'active'
  const selectedPool = overview?.pools.find(item => item.id === pool)
  const lastAction = session?.actions.at(-1)
  return <div className="dojo">
    <header className="dojo-header"><div><p className="eyebrow">ZHIXING PRACTICE / 训练与复盘</p><h1>A股 K线训练<span>道场</span></h1><p>把判断交给当下，把答案留给下一根 K 线。</p></div><button className="dojo-button" disabled={busy} onClick={() => void run(reload)}><RefreshCw size={15} className={busy ? 'spin' : ''}/>刷新记录</button></header>
    {error && <div className="dojo-error" role="alert">{error}<button onClick={() => void run(reload)} disabled={busy}>重新加载</button></div>}
    {!session ? <>
      <section className="dojo-intro"><div className="dojo-intro-copy"><span className="dojo-kicker">BLIND REPLAY / 历史盲练</span><h2>先读懂走势，<br/>再检验你的判断。</h2><p>随机抽取一段真实 A 股历史，隐藏名称与日期。<br/>逐日决策，在复盘中找到自己的交易习惯。</p><div className="dojo-intro-tags"><span><EyeOff size={15}/>隐藏标的与日期</span><span><ShieldCheck size={15}/>只用已揭示行情</span></div></div><div className="dojo-intro-art" aria-hidden="true"><CandlestickChart/><span>观察 → 决策 → 推演 → 复盘</span><b>下一根，会怎样？</b></div></section>
      <div className="dojo-setup-layout"><section className="dojo-setup"><div className="dojo-section-title"><h2><Target size={19}/>开始一局训练</h2><span>虚拟本金 ¥100,000</span></div><fieldset disabled={busy}><legend>01 / 选择题库</legend><div className="dojo-pool-options">{[{id: 'reference', title: '主板参考池', desc: '沿用项目现有沪深主板股票'}, {id: 'watchlist', title: '我的主板自选', desc: '从已保存的主板自选中随机抽取'}].map(item => <button key={item.id} className={pool === item.id ? 'selected' : ''} aria-pressed={pool === item.id} onClick={() => setPool(item.id)}><div><strong>{item.title}</strong><span>{overview?.pools.find(p => p.id === item.id)?.count ?? '—'} 只</span></div><small>{item.desc}</small>{pool === item.id && <Check size={16}/>}</button>)}</div></fieldset><fieldset disabled={busy}><legend>02 / 推演时长</legend><div className="dojo-duration">{[20, 40, 60].map(value => <button key={value} aria-pressed={steps === value} onClick={() => setSteps(value)}><strong>{value}</strong> 个交易日<small>{value === 20 ? '短程热身' : value === 40 ? '标准训练' : '耐心进阶'}</small></button>)}</div></fieldset><div className="dojo-start-info"><BookOpen size={16}/><span>先展示 60 根日 K 线，每次操作推进 1 个交易日。</span></div><button className="dojo-primary" disabled={busy || !selectedPool?.count} onClick={() => void run(start)}>{busy ? <LoaderCircle className="spin" size={18}/> : <Shuffle size={18}/>} {busy ? '正在读取训练数据…' : '随机抽取 · 开始盲练'}<ArrowRight size={18}/></button>{selectedPool?.count === 0 && <p className="dojo-hint">此题库暂无股票，请选择主板参考池，或先在个股研究中添加主板自选。</p>}<p className="dojo-hint">首次抽题需联网；已有 {overview?.cache_count ?? 0} 只历史行情缓存。不含 ETF、创业板、科创板、北交所及当前名称含 ST／退的股票。</p></section><section className="dojo-practice-summary"><span className="dojo-kicker">YOUR PRACTICE</span><h2>每一局，都留下经验。</h2><div className="dojo-summary-grid"><div><strong>{overview?.summary.completed ?? 0}</strong><span>完整训练</span></div><div><strong>{overview?.summary.win_rate == null ? '—' : `${overview.summary.win_rate}%`}</strong><span>盈利局占比</span></div><div><strong>{pct(overview?.summary.average_return)}</strong><span>平均收益</span></div><div><strong>{pct(overview?.summary.best_return)}</strong><span>最佳收益</span></div></div><p>统计仅包含走完全部交易日的训练。提前结束的记录保留供复盘。</p><div className="dojo-summary-tip"><ShieldCheck size={20}/><span>训练进度和复盘记录<br/>自动保存在本机</span></div></section></div>
    </> : <>
      <div className="dojo-session-banner"><div><span className={`dojo-state ${active ? '' : 'finished'}`}>{active ? <EyeOff size={15}/> : <Check size={15}/>} {active ? '盲练进行中' : session.status === 'completed' ? '训练完成 · 已揭晓' : '提前结束 · 已揭晓'}</span><span>{session.step} / {session.total_steps} 个交易日</span></div><div>{active ? <button className="dojo-link" onClick={() => setConfirmEnd(!confirmEnd)} disabled={busy}><Flag size={15}/>结束并复盘</button> : <button className="dojo-button" onClick={() => {setSession(null); setConfirmEnd(false)}}>返回训练大厅<ArrowRight size={15}/></button>}</div></div>
      <progress className="dojo-progress" value={session.step} max={session.total_steps} aria-label="训练进度"/>
      {confirmEnd && <div className="dojo-end-confirm" role="alert"><span>将揭晓标的并保存当前复盘，本局不能继续，也不计入完整训练统计。</span><button className="dojo-button" onClick={() => setConfirmEnd(false)}>继续训练</button><button className="dojo-button" disabled={busy} onClick={() => void run(() => act('finish'))}>确认结束</button></div>}
      <div className="dojo-account">{[{label:'账户总资产', value:`¥${money(session.metrics.equity)}`, extra:`可用资金 ¥${money(session.cash)}`}, {label:'本局收益', value:pct(session.metrics.return_pct), extra:`相对买入持有 ${session.metrics.excess_pct >= 0 ? '+' : ''}${session.metrics.excess_pct.toFixed(2)} 个百分点`, color:session.metrics.return_pct}, {label:'当前仓位', value:`${session.metrics.position_pct.toFixed(1)}%`, extra:`持仓 ${session.shares.toLocaleString()} 股`}, {label:'最大回撤', value:`${session.metrics.max_drawdown_pct.toFixed(2)}%`, extra:`累计费用 ¥${money(session.metrics.fees)}`}].map(item => <article key={item.label}><span>{item.label}</span><strong className={item.color === undefined ? '' : tone(item.color)}>{item.value}</strong><small>{item.extra}</small></article>)}</div>
      <div className="dojo-play-layout"><TrainingChart key={session.id} session={session}/><section className="dojo-order"><span className="dojo-kicker">{active ? 'YOUR NEXT MOVE' : 'SESSION REVIEW'}</span><h2>{active ? '下一步，由你决定' : '答案已经揭晓'}</h2>{active ? <><p>基于当前已知走势决策。<br/>点击后按下一交易日开盘价模拟成交。</p><fieldset disabled={busy}><legend>买入使用可用资金 / 卖出使用持仓</legend><div className="dojo-fractions">{[{v:.25, t:'1/4'}, {v:.5, t:'1/2'}, {v:1, t:'全部'}].map(item => <button key={item.v} aria-pressed={fraction === item.v} onClick={() => setFraction(item.v)}>{item.t}</button>)}</div></fieldset><label className="dojo-note">这次判断的理由 <span>选填</span><textarea value={note} maxLength={160} disabled={busy} onChange={event => setNote(event.target.value)} placeholder="例如：回踩均线后缩量企稳，试仓观察" rows={3}/></label><div className="dojo-actions"><button className="dojo-buy" disabled={busy || session.cash < 5} onClick={() => void run(() => act('buy'))}><ArrowUpRight size={18}/>买入并推进</button><button className="dojo-sell" disabled={busy || session.shares === 0} onClick={() => void run(() => act('sell'))}>卖出并推进</button><button className="dojo-hold" disabled={busy} onClick={() => void run(() => act('hold'))}>{busy ? <LoaderCircle className="spin" size={17}/> : <ChevronRight size={18}/>}观望 · 下一交易日</button></div><p className="dojo-hint">每次只执行一个操作，再展示新日线；买入当天不能卖出。未成交也推进一天。</p>{lastAction && <div className={`dojo-fill ${lastAction.status === 'rejected' ? 'rejected' : ''}`} role="status"><strong>第 {lastAction.step} 日 · {lastAction.status === 'filled' ? '已成交' : lastAction.status === 'rejected' ? '未成交' : '已观望'}</strong><span>{lastAction.reason}{lastAction.shares > 0 ? ` · ${lastAction.shares} 股 @ ${lastAction.price?.toFixed(2)}` : ''}</span></div>}</> : <><h3>{session.reveal?.stock_name}</h3><p>{session.reveal?.stock_code}<br/>{session.step ? `${session.reveal?.start_date} 至 ${session.reveal?.end_date}` : '未进行推演'}</p><span className="dojo-review-label">规则复盘 · 自动统计</span>{session.reveal?.notes.map((text, index) => <p className="dojo-review-note" key={text}><span>0{index + 1}</span>{text}</p>)}</>}</section></div>
      <EquityChart session={session}/>
      <section className="dojo-trades"><div className="dojo-section-title"><h2><History size={18}/>决策记录</h2><span>{session.metrics.trades} 笔成交 · {session.actions.length} 次决策</span></div>{!session.actions.length ? <p className="dojo-record-empty">还没有决策。读完左侧走势，记录你的第一步判断。</p> : <div className="dojo-table-scroll"><table><thead><tr><th>推演日</th><th>操作</th><th>成交数量 / 价格</th><th>费用</th><th>判断与结果</th></tr></thead><tbody>{session.actions.slice().reverse().map(action => <tr key={action.step}><td>第 {action.step} 日</td><td className={action.action === 'buy' ? 'dojo-up' : action.action === 'sell' ? 'dojo-down' : ''}>{action.action === 'buy' ? '买入' : action.action === 'sell' ? '卖出' : '观望'}</td><td>{action.shares ? `${action.shares} 股 / ${action.price?.toFixed(2)}` : '—'}</td><td>{action.fee ? money(action.fee) : '—'}</td><td><strong>{action.note || '未填写判断理由'}</strong><small>{action.reason}</small></td></tr>)}</tbody></table></div>}</section>
    </>}
    <details className="dojo-rules"><summary><ShieldCheck size={17}/>训练规则与数据口径<ChevronRight size={16}/></summary><div><p>沪深主板日线训练，10 万虚拟本金，只做多、100 股整手买卖。每个交易日仅一次操作，收盘后决策、下一日开盘模拟成交，遵守 T+1。周线是辅助视图，操作仍逐日执行。</p><p>固定模拟费用：双边佣金万分之三、每笔最低 5 元；卖出另收万分之五。未单列过户费，不回放历年费率，不计滑点。仓位比例按下一开盘时可用资金／持仓计算，费用计入资金预算。</p><p>使用腾讯前复权历史价，既有缓存可离线复用，非当年的实际委托价格；零成交量不成交，单一价上涨不买入、单一价下跌不卖出。缺少逐日 ST 状态、涨跌停价、盘口和排队数据，未完整模拟涨跌停及除权派息。参考池有存续及选样偏差。</p><p>基准为同标的在训练期首个可成交开盘买入并持有，采用相同整手、佣金与本金，期末按收盘估值。最大回撤使用每日收盘总权益；无强制平仓。训练时后端仅返回已揭示行情；复盘为规则统计，未接入 AI 评价。</p>{session && <p>本局数据：{session.data_source}{session.reveal ? `；采集于 ${new Date(session.reveal.fetched_at).toLocaleString('zh-CN')}` : '；结束后展示股票与行情日期'}。规则版本：{session.rules_version}</p>}<p><a href="https://www.sse.com.cn/lawandrules/sselawsrules2025/stocks/exchange/c/c_20260424_10816482.shtml" target="_blank" rel="noreferrer">上交所交易规则</a> · <a href="https://fgk.chinatax.gov.cn/zcfgk/c102416/c5211343/content.html" target="_blank" rel="noreferrer">印花税政策来源</a></p></div></details>
    {!active && <section className="dojo-history"><div className="dojo-section-title"><h2><History size={18}/>最近训练</h2><span>仅本机保存 · 最近 30 局</span></div>{!overview?.history.length ? <p className="dojo-record-empty">第一局训练完成后，你的交易足迹会留在这里。</p> : overview.history.map(item => <button key={item.id} disabled={busy} onClick={() => void run(async () => {setSession(await trainingApi.get(item.id)); setConfirmEnd(false)})}><div><strong>{item.stock_name}</strong><small>{new Date(item.created_at).toLocaleDateString('zh-CN')} · {item.step}/{item.total_steps} 日 · {item.status === 'completed' ? '完整训练' : item.status === 'active' ? '进行中' : '提前结束'}</small></div><span className={tone(item.metrics.return_pct)}>{pct(item.metrics.return_pct)}</span><ChevronRight size={17}/></button>)}</section>}
    <p className="dojo-footnote">历史行情推演，仅用于学习与复盘，不连接真实交易账户。</p>
  </div>
}
