"""Build fictional demo fixtures with the production rule engine; no network or user data."""
from __future__ import annotations

import json
import random
import sys
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services/desktop-api"))
from app.models import ScoreInput  # noqa: E402
from app.scoring import StrategyEngine  # noqa: E402


def build() -> dict:
    engine = StrategyEngine(ROOT / "packages/strategy-spec/group-original-v1.json")
    # Names, codes, quotes and paths are fictional. Scores are real engine output.
    examples = [
        ("星河半导体", "半导体", 48.6, 1.82, .21, .24, .068, 2.8, 3, .18, "stock"),
        ("远山能源", "核电", 26.3, 2.14, .48, .51, .034, 1.8, 2, .11, "stock"),
        ("青禾消费", "食品饮料", 32.8, .76, .52, .55, .008, .7, 1, .06, "stock"),
        ("云帆制造", "机械设备", 18.2, .32, .78, .72, .008, -.8, 0, -.06, "stock"),
        ("海川银行", "银行", 12.6, -.42, .82, .84, -.055, -1.8, -2, -.12, "stock"),
        ("新衡医药", "医疗", 39.4, 1.26, .38, .44, .025, 1.2, 2, .09, "stock"),
        ("宽基样本 ETF", "宽基", 3.82, .65, .48, .51, .006, .5, 0, .05, "etf"),
        ("科技样本 ETF", "半导体", 1.26, 2.52, .35, .45, .034, 2.8, 0, .14, "etf"),
    ]
    days = []
    day = date(2026, 8, 28)
    while len(days) < 120:
        if day.weekday() < 5:
            days.append(day.isoformat())
        day -= timedelta(days=1)
    days.reverse()
    stocks = []
    for index, (name, sector, price, change, pe_rank, pb_rank, flow, sector_change, quality, drift, kind) in enumerate(examples):
        rng = random.Random(420 + index)
        closes = [price * (1 - drift)]
        for i in range(1, 119):
            closes.append(max(.1, closes[-1] * (1 + drift / 120 + rng.uniform(-.013, .014))))
        scale = (price / (1 + change / 100)) / closes[-1]
        closes = [value * scale for value in closes] + [price]
        bars = []
        for i, close in enumerate(closes):
            opening = (closes[i - 1] if i else close) * (1 + rng.uniform(-.004, .004))
            bars.append({"date": days[i], "open": round(opening, 3), "close": round(close, 3),
                         "high": round(max(opening, close) * (1 + rng.uniform(.003, .017)), 3),
                         "low": round(min(opening, close) * (1 - rng.uniform(.003, .017)), 3),
                         "volume": rng.randrange(150, 780)})
        inputs = ScoreInput(stock_code=f"demo{index + 1:02}", stock_name=name, sector=sector,
                            price=price, pe=round(12 + pe_rank * 40, 2), pb=round(1 + pb_rank * 5, 2),
                            pe_percentile=pe_rank, pb_percentile=pb_rank, change_pct=change,
                            turnover_pct=2.4, amplitude_pct=4.2, main_flow_ratio=flow,
                            sector_change_pct=sector_change, quality_score=quality,
                            ma5=sum(closes[-5:]) / 5, ma10=sum(closes[-10:]) / 10,
                            ma20=sum(closes[-20:]) / 20, in_rotation_pool=index == 0, mode="review")
        stocks.append({"code": inputs.stock_code, "name": name, "sector": sector, "kind": kind,
                       "input": inputs.model_dump(), "score": engine.score(inputs).model_dump(), "bars": bars})
    return {"version": "zhixing-demo-2026-09-05-v1", "asOf": "2026-08-28",
            "source": "合成演示数据", "thresholds": engine.config["grade_thresholds"], "stocks": stocks}


if __name__ == "__main__":
    payload = build()
    target = ROOT / "demo/data.js"
    target.parent.mkdir(exist_ok=True)
    target.write_text("// Generated by scripts/build_demo_data.py. All instruments and market data are fictional.\n"
                      + "window.ZHIXING_DEMO = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    print("Built", target.relative_to(ROOT), [(s["code"], s["score"]["grade"], s["score"]["total_score"]) for s in payload["stocks"]])
